'use strict';
const STORAGE='shizufi.v2',OLD_STORAGE='shizufi.v1',F=Finance;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:6}).format(v);
const money=(v,c='IDR')=>new Intl.NumberFormat('id-ID',{style:'currency',currency:c,maximumFractionDigits:F.currencies[c]}).format(v);
const date=v=>new Date(v).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'});
const labels={bank:'Bank',cash:'Cash',ewallet:'E-Wallet',investment:'Investasi',credit_card:'Kartu kredit',loan:'Pinjaman',other:'Lainnya',income:'Pemasukan',expense:'Pengeluaran',transfer:'Transfer',adjustment:'Koreksi',buy:'Beli emas',sell:'Jual emas',opening:'Emas awal'};
const cloud=typeof CloudStore!=='undefined'&&CloudStore.enabled;
let saving=false;
let state=F.empty(),filter='all',blocked=false,marketMessage='Mengambil harga terbaru…',priceRequest=0;
function notify(message,error=false){$('#notice').textContent=message;$('#notice').classList.toggle('error',error);}
if(!cloud)try{const saved=localStorage.getItem(STORAGE),old=localStorage.getItem(OLD_STORAGE);if(saved)state=F.read(JSON.parse(saved));else if(old){state=F.read(JSON.parse(old));localStorage.setItem(STORAGE,JSON.stringify(state));notify('Catatan lama dimigrasikan ke akun dan ledger. Backup v1 tetap disimpan.');}}catch(err){blocked=true;notify(`Data lokal tidak dapat dibaca: ${err.message} Ekspor data asli atau impor backup valid. Penyimpanan otomatis dihentikan.`,true);}
async function commit(next){
  if(blocked)throw Error('Penyimpanan belum siap. Login atau periksa data lokal terlebih dahulu.');
  if(saving)throw Error('Penyimpanan sedang berlangsung. Tunggu lalu coba lagi.');
  F.validate(next,{rebuildPositions:false});
  if(cloud){saving=true;$('#sync-status').textContent='Menyimpan ke server…';try{state=F.read(await CloudStore.save(next));$('#sync-status').textContent='Tersimpan di server';}catch(err){$('#sync-status').textContent='Gagal menyimpan · data terakhir dipertahankan';if(err.status===401){bootServer();}throw err;}finally{saving=false;}}
  else{try{localStorage.setItem(STORAGE,JSON.stringify(next));}catch{throw Error('Penyimpanan gagal. Periksa izin / ruang browser dan ekspor backup.');}state=next;}
  render();
}
function toIDR(value,currency){if(currency==='IDR')return value;const r=state.market?.rates;return r?.[currency]&&r.IDR?value/r[currency]*r.IDR:null;}
function holdings(){const totals=F.balances(state);const result=state.accounts.filter(a=>a.status==='active').map(a=>({id:a.id,type:'fiat',name:a.name,location:state.institutions.find(i=>i.id===a.institution_id)?.name||labels[a.account_type],note:a.note,currency:a.currency,balance:totals[a.id]/10**F.currencies[a.currency],account:a}));for(const p of state.positions){if(!p.quantity_micrograms)continue;const i=state.instruments.find(i=>i.id===p.instrument_id),a=state.accounts.find(a=>a.id===p.account_id);result.push({id:p.id,type:'gold',name:i.name,location:a.name,note:i.note,grams:p.quantity_micrograms/1e6,purity:i.purity,cost:p.cost_basis_minor,position:p,instrument:i});}return result;}
function valueOf(a){return a.type==='gold'?state.market?.goldIDR?a.grams*a.purity/100*state.market.goldIDR:null:toIDR(a.balance,a.currency);}
function render(){
  const assets=holdings();let fiat=0,gold=0,unknown=0,pure=0,cost=0,priced=0,hasCost=false,realized=0,unknownRealized=false;
  for(const a of assets){const v=valueOf(a);if(v===null)unknown++;else if(a.type==='fiat')fiat+=v;else gold+=v;if(a.type==='gold'){pure+=a.grams*a.purity/100;if(a.cost!==null&&v!==null){cost+=a.cost;priced+=v;hasCost=true;}}}
  for(const p of state.positions){if(p.realized_pnl_minor===null)unknownRealized=true;else realized+=p.realized_pnl_minor;}
  $('#total').textContent=money(fiat+gold);$('#fiat-total').textContent=money(fiat);$('#gold-total').textContent=money(gold);
  $('#total-note').textContent=unknown?`${unknown} aset belum dinilai · total sementara`:'Nilai bersih fiat + emas (saldo utang mengurangi total)';
  $('#fiat-count').textContent=`${state.accounts.filter(a=>a.status==='active').length} akun aktif`;$('#gold-count').textContent=`${number(pure)} gram emas murni`;$('#asset-count').textContent=assets.length;
  const denominator=Math.max(0,fiat)+gold,pct=denominator?Math.max(0,fiat)/denominator*100:0;
  $('#donut').style.background=denominator?`conic-gradient(var(--green) 0% ${pct}%,var(--gold) ${pct}% 100%)`:'conic-gradient(#e7ebe4 0% 100%)';$('#fiat-percent').textContent=`${number(pct)}%`;$('#gold-percent').textContent=`${number(denominator?100-pct:0)}%`;
  $('#profit').textContent=(hasCost?`Selisih belum direalisasi: ${money(priced-cost)}. `:'Modal tidak diketahui tidak dihitung dalam selisih. ')+`Laba/rugi terealisasi: ${money(realized)}${unknownRealized?' + penjualan bermodal tidak diketahui':''}.${fiat<0?' Komposisi memakai fiat neto positif; utang tercermin pada total.':''}`;
  $('#gold-price').textContent=state.market?.goldIDR?money(state.market.goldIDR):'Belum tersedia';$('#price-status').textContent=marketMessage;
  const visible=assets.filter(a=>filter==='all'||a.type===filter);$('#empty').hidden=visible.length>0;$('#empty h3').textContent=assets.length?'Belum ada aset di kategori ini':'Mulai dari akun pertamamu';
  $('#rows').innerHTML=visible.map(a=>{const v=valueOf(a),delta=a.type==='gold'&&a.cost!==null&&v!==null?v-a.cost:null;return `<tr><td><strong>${esc(a.name)}</strong><small>${a.type==='gold'?'◇ Emas':'↗ '+labels[a.account.account_type]} · ${esc(a.location)}</small>${a.note?`<small>${esc(a.note)}</small>`:''}</td><td>${a.type==='gold'?`${number(a.grams)} g<small>Kemurnian ${number(a.purity)}%</small>`:money(a.balance,a.currency)}</td><td><strong>${v===null?'Belum tersedia':money(v)}</strong></td><td class="${delta===null?'':delta>=0?'positive':'negative'}">${delta===null?'—':money(delta)}</td><td>${a.type==='fiat'?`<button data-edit="${esc(a.id)}">Edit / koreksi</button><button data-archive="${esc(a.id)}">Arsip</button>`:`<button data-trade="${esc(a.position.account_id)}" data-instrument="${esc(a.instrument.id)}">Beli / jual</button>`}</td></tr>`;}).join('');
  $('#events').innerHTML=state.transactions.length?[...state.transactions].sort((a,b)=>Date.parse(b.transaction_date)-Date.parse(a.transaction_date)).slice(0,50).map(t=>{const trade=state.investment_transactions.find(i=>i.transaction_id===t.id),category=state.categories.find(c=>c.id===t.category_id),entries=state.transaction_entries.filter(e=>e.transaction_id===t.id);return `<li><details class="ledger-detail"><summary><strong>${esc(t.description)}</strong><span>${labels[trade?.type]||labels[t.transaction_type]}${category?' · '+esc(category.name):''} · ${date(t.transaction_date)}</span></summary>${trade?`<p>${number(trade.quantity_micrograms/1e6)} g · ${esc(state.instruments.find(i=>i.id===trade.instrument_id).name)} · ${trade.total_minor===null?'Modal tidak diketahui':money(trade.total_minor)} · biaya ${money(trade.fee_minor)} · pajak ${money(trade.tax_minor)}</p>`:''}<ul>${entries.map(e=>`<li><span>${esc(e.account_id?state.accounts.find(a=>a.id===e.account_id).name:'Penyeimbang: '+e.offset_type)}</span><strong>${money(e.amount_minor/10**F.currencies[e.currency],e.currency)}</strong></li>`).join('')}</ul></details></li>`;}).join(''):'<li class="muted">Transaksi akan muncul setelah kamu membuat akun atau mencatat kepemilikan.</li>';
}
const form=$('#asset-form'),dialog=$('#asset-dialog'),txForm=$('#transaction-form'),txDialog=$('#transaction-dialog');
const options=(items,name)=>'<option value="">Pilih…</option>'+items.map(a=>`<option value="${esc(a.id)}">${esc(name(a))}</option>`).join('');
function switchFields(){const gold=form.elements.type.value==='gold';$('#gold-fields').hidden=!gold;$('#fiat-fields').hidden=gold;for(const key of ['account_id','grams','purity'])form.elements[key].required=gold;form.elements.balance.required=!gold;}
function openForm(key){form.reset();form.elements.id.value='';for(const field of ['type','currency','account_type','institution'])form.elements[field].disabled=false;$('#gold-account').innerHTML=options(state.accounts.filter(a=>a.status==='active'&&a.account_type==='investment'),a=>a.name);const a=state.accounts.find(a=>a.id===key);if(a){form.elements.id.value=a.id;form.elements.name.value=a.name;form.elements.type.value='fiat';form.elements.note.value=a.note;form.elements.account_type.value=a.account_type;form.elements.currency.value=a.currency;form.elements.institution.value=state.institutions.find(i=>i.id===a.institution_id)?.name||'';form.elements.balance.value=F.balance(state,a.id)/10**F.currencies[a.currency];for(const field of ['type','currency','account_type','institution'])form.elements[field].disabled=true;}$('#dialog-title').textContent=a?'Edit akun / koreksi saldo':'Tambah akun / emas';switchFields();dialog.showModal();}
$('#add').onclick=()=>openForm();$('#empty-add').onclick=()=>openForm();$('#close').onclick=()=>dialog.close();form.elements.type.onchange=switchFields;
form.onsubmit=async e=>{e.preventDefault();const input=Object.fromEntries(new FormData(form)),key=form.elements.id.value;try{const next=key?F.updateAccount(state,key,input):input.type==='gold'?F.createGold(state,input):F.createAccount(state,input);await commit(next);dialog.close();notify('Catatan tersimpan; saldo dan posisi diperbarui dari ledger.');}catch(err){notify(err.message,true);}};
function txFields(){const type=txForm.elements.type.value,trade=['buy','sell'].includes(type),transfer=type==='transfer';$('#trade-fields').hidden=!trade;$('#destination-field').hidden=!transfer;$('#category-fields').hidden=!['income','expense'].includes(type);const source=state.accounts.find(a=>a.id===txForm.elements.account_id.value),dest=state.accounts.find(a=>a.id===txForm.elements.destination_id.value),cross=transfer&&source&&dest&&source.currency!==dest.currency;$('#received-field').hidden=!cross;txForm.elements.received.required=!!cross;txForm.elements.destination_id.required=transfer;for(const key of ['investment_account_id','instrument_id','grams'])txForm.elements[key].required=trade;$('#amount-label span').textContent=trade?'Nilai bruto emas (IDR)':`Jumlah (${source?.currency||'mata uang akun'})${type==='adjustment'?' · positif / negatif':''}`;txForm.elements.amount.min=type==='adjustment'?'':trade?'1':'0.01';$('#tx-category').innerHTML='<option value="">Tanpa kategori</option>'+state.categories.filter(c=>c.type===type).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');}
function openTransaction(aid,iid){if(!state.accounts.some(a=>a.status==='active')){notify('Buat akun terlebih dahulu.',true);return;}txForm.reset();const active=state.accounts.filter(a=>a.status==='active');$('#tx-account').innerHTML=options(active,a=>`${a.name} (${a.currency})`);$('#tx-destination').innerHTML=options(active,a=>`${a.name} (${a.currency})`);$('#tx-investment').innerHTML=options(active.filter(a=>a.account_type==='investment'),a=>a.name);$('#tx-instrument').innerHTML=options(state.instruments,i=>`${i.name} · ${number(i.purity)}%`);txForm.elements.date.value=new Date(Date.now()+7*3600000).toISOString().slice(0,16);if(aid){txForm.elements.type.value='buy';txForm.elements.investment_account_id.value=aid;txForm.elements.instrument_id.value=iid;}txFields();txDialog.showModal();}
$('#transaction-add').onclick=()=>openTransaction();$('#transaction-close').onclick=()=>txDialog.close();for(const key of ['type','account_id','destination_id'])txForm.elements[key].onchange=txFields;
txForm.onsubmit=async e=>{e.preventDefault();const input=Object.fromEntries(new FormData(txForm));try{input.date=new Date(input.date+':00+07:00').toISOString();if($('#category-fields').hidden){input.category_id='';input.new_category='';}await commit(F.transact(state,input));txDialog.close();notify('Transaksi dan entri ledger tersimpan.');}catch(err){notify(err.message,true);}};
$('#rows').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)openForm(b.dataset.edit);if(b.dataset.trade)openTransaction(b.dataset.trade,b.dataset.instrument);if(b.dataset.archive){try{await commit(F.archive(state,b.dataset.archive));notify('Akun diarsipkan; riwayat tetap tersimpan.');}catch(err){notify(err.message,true);}}};
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));render();});
async function fetchJSON(url){const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('API tidak tersedia.');return r.json();}
function withMarket(m){const n=F.clone(state);n.market=m;if(m.goldIDR)n.market_prices=[...new Map([...n.market_prices,...n.instruments.map(i=>({instrument_id:i.id,price:m.goldIDR*i.purity/100,currency:'IDR',timestamp:m.goldAt||m.fetchedAt,source:m.mode}))].map(p=>[JSON.stringify([p.instrument_id,p.timestamp,p.source]),p])).values()].slice(-5000);if(m.fxAt)n.exchange_rates=Object.entries(m.rates).filter(([code])=>Object.hasOwn(F.currencies,code)).map(([code,rate])=>({base_currency:'USD',quote_currency:code,rate,timestamp:m.fxAt,source:'ExchangeRate-API'}));return n;}
async function refreshPrices(){if(blocked)return;const request=++priceRequest;$('#refresh').disabled=true;marketMessage='Mengambil harga terbaru…';render();try{const [g,f]=await Promise.allSettled([fetchJSON('https://api.gold-api.com/price/XAU'),fetchJSON('https://open.er-api.com/v6/latest/USD')]);if(request!==priceRequest)return;const goodFX=f.status==='fulfilled'&&f.value.result==='success'&&Object.keys(F.currencies).every(c=>Number.isFinite(f.value.rates?.[c])&&f.value.rates[c]>0)&&Number.isFinite(f.value.time_last_update_unix),goodGold=g.status==='fulfilled'&&Number.isFinite(g.value.price)&&g.value.price>0&&Number.isFinite(Date.parse(g.value.updatedAt));if(!goodFX)throw Error('Kurs tidak tersedia.');const fresh=goodFX&&goodGold,old=state.market,at=new Date().toISOString(),market={mode:fresh?'spot':old?.mode||'spot',goldIDR:fresh?g.value.price/31.1034768*f.value.rates.IDR:old?.goldIDR??null,goldAt:fresh?g.value.updatedAt:old?.goldAt??null,fxAt:new Date(f.value.time_last_update_unix*1000).toISOString(),rates:f.value.rates,fetchedAt:at};await commit(withMarket(market));marketMessage=fresh?`Spot · harga ${date(market.goldAt)} · kurs ${date(market.fxAt)}`:`Kurs diperbarui · emas ${market.goldIDR?'memakai harga tersimpan / manual dari '+date(market.goldAt||old.fetchedAt):'belum tersedia'}.`;}catch(err){marketMessage=state.market?.goldIDR?`Pembaruan gagal · ${state.market.mode==='manual'?'harga manual':'cache spot'} dari ${date(state.market.goldAt||state.market.fetchedAt)} · kurs ${state.market.fxAt?date(state.market.fxAt):'belum tersedia'}.`:'Harga belum tersedia. Periksa internet atau isi harga emas manual.';}finally{if(request===priceRequest){$('#refresh').disabled=false;render();}}}
$('#refresh').onclick=refreshPrices;
$('#price-form').onsubmit=async e=>{e.preventDefault();const price=Number(new FormData(e.target).get('price'));if(!Number.isFinite(price)||price<=0)return;const at=new Date().toISOString();try{priceRequest++;$('#refresh').disabled=false;await commit(withMarket({mode:'manual',goldIDR:price,goldAt:at,fxAt:state.market?.fxAt??null,rates:state.market?.rates??{},fetchedAt:at}));marketMessage=`Harga manual · ${date(at)}. Diganti spot saat pembaruan otomatis berikutnya berhasil.`;render();notify('Harga manual tersimpan.');}catch(err){notify(err.message,true);}};
$('#export').onclick=()=>{let contents=JSON.stringify(state,null,2);if(blocked&&!cloud)contents=localStorage.getItem(STORAGE)||localStorage.getItem(OLD_STORAGE)||contents;const url=URL.createObjectURL(new Blob([contents],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`shizufi-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Backup diekspor. Simpan file di tempat pribadi.');};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('Backup maksimal 10 MB.');const next=F.read(JSON.parse(await file.text()));if(!confirm(`Ganti workspace saat ini dengan ${next.accounts.length} akun dan ${next.transactions.length} transaksi dari backup? Ekspor data saat ini terlebih dahulu.`))return;const wasBlocked=blocked;blocked=false;try{await commit(next);}catch(err){blocked=wasBlocked;throw err;}notify('Backup diimpor; posisi dihitung ulang dari transaksi.');await refreshPrices();}catch(err){notify(`Impor gagal: ${err.message}`,true);}finally{e.target.value='';}};
let setupRequired=false;
function showAuth(message){blocked=true;priceRequest++;dialog.close();txDialog.close();document.body.classList.add('auth-required');$('#auth-panel').hidden=false;$('#server-toolbar').hidden=true;$('#auth-status').textContent=message;}
async function enterWorkspace(){const saved=await CloudStore.load();state=saved?F.read(saved):F.empty();blocked=false;if(!saved)await commit(state);document.body.classList.remove('auth-required');$('#auth-panel').hidden=true;$('#server-toolbar').hidden=false;$('#sync-status').textContent='Terhubung · data tersimpan di server';$('footer span').textContent='Workspace pribadi · PHP + MySQL';$('.side-note').innerHTML='<span class="status-dot"></span> Database Hostinger<p>Login pribadi · lintas perangkat<br>Ekspor backup secara berkala.</p>';$('#migrate-local').hidden=!(localStorage.getItem(STORAGE)||localStorage.getItem(OLD_STORAGE));marketMessage=state.market?.goldIDR?`Harga tersimpan · ${date(state.market.goldAt||state.market.fetchedAt)}`:'Mengambil harga terbaru…';render();refreshPrices();}
async function bootServer(){showAuth('Menghubungkan ke server…');$('#auth-form').hidden=true;try{const info=await CloudStore.session();setupRequired=info.setup_required;$('#auth-title').textContent=setupRequired?'Buat akun pemilik':'Masuk ke workspace';$('#setup-fields').hidden=!setupRequired;const auth=$('#auth-form');auth.elements.name.required=setupRequired;auth.elements.setup_token.required=setupRequired;auth.elements.password.minLength=setupRequired?12:1;auth.elements.password.autocomplete=setupRequired?'new-password':'current-password';$('#auth-submit').textContent=setupRequired?'Buat akun pemilik':'Masuk';if(info.authenticated){await enterWorkspace();return;}$('#auth-form').hidden=false;$('#auth-status').textContent=setupRequired?'Database siap. Daftarkan satu akun pemilik menggunakan kunci instalasi.':'Masuk untuk membuka data pribadi dari server.';}catch(err){$('#auth-status').textContent=err.message;}}
if(cloud){
  $('#auth-retry').onclick=bootServer;
  $('#auth-form').onsubmit=async e=>{e.preventDefault();$('#auth-submit').disabled=true;try{await CloudStore.login(Object.fromEntries(new FormData(e.target)),setupRequired);e.target.elements.password.value='';e.target.elements.setup_token.value='';await enterWorkspace();}catch(err){$('#auth-status').textContent=err.message;}finally{$('#auth-submit').disabled=false;}};
  $('#logout').onclick=async()=>{if(saving){notify('Tunggu sampai penyimpanan selesai.',true);return;}try{await CloudStore.logout();state=F.empty();render();await bootServer();}catch(err){notify('Logout gagal: '+err.message,true);}};
  $('#migrate-local').onclick=async()=>{try{const raw=localStorage.getItem(STORAGE)||localStorage.getItem(OLD_STORAGE),next=F.read(JSON.parse(raw));if(!confirm(`Impor ${next.accounts.length} akun dari browser ini dan mengganti workspace server? Ekspor backup server terlebih dahulu.`))return;await commit(next);$('#migrate-local').hidden=true;notify('Data browser dimigrasikan ke server. Salinan lokal tidak dihapus.');}catch(err){notify(err.message,true);}};
}
render();
if(cloud){blocked=true;bootServer();}else{if(typeof document.body!=='undefined')document.body.classList.remove('auth-required');refreshPrices();}
