const {test}=require('node:test');
const assert=require('node:assert/strict');
const F=require('../model.js');
const vm=require('node:vm'),fs=require('node:fs');
const at='2026-10-03T00:00:00Z';
function account(s,name='Kas',currency='IDR',type='cash',amount=0){return F.createAccount(s,{name,currency,account_type:type,balance:amount,date:at});}
function setup(){let s=account(F.empty(),'Bank','IDR','bank',20000000),cash=s.accounts[0].id;s=account(s,'Brankas','IDR','investment');const inv=s.accounts[1].id;s=F.createGold(s,{account_id:inv,name:'Antam',purity:99.99,grams:0,cost:''});return {s,cash,inv,instr:s.instruments[0].id};}
function trade(s,cash,inv,instr,type='buy',grams=10,amount=10000000,date=at,fee=0,tax=0){return F.transact(s,{account_id:cash,investment_account_id:inv,instrument_id:instr,type,grams,amount,fee,tax,date,description:type});}
test('minor units avoid floating-point accumulation of cash',()=>{let s=account(F.empty(),'Dollar','USD');const aid=s.accounts[0].id;for(let i=0;i<100;i++)s=F.transact(s,{type:'income',account_id:aid,amount:.1,description:'Income',date:at});assert.equal(F.balance(s,aid),1000);});
test('same currency transfer changes two accounts without changing net cash',()=>{let s=account(F.empty(),'Bank','IDR','bank',1000000);s=account(s,'Dompet');const [a,b]=s.accounts;s=F.transact(s,{type:'transfer',account_id:a.id,destination_id:b.id,amount:250000,description:'Tarik tunai',date:at});assert.equal(F.balance(s,a.id),750000);assert.equal(F.balance(s,b.id),250000);assert.equal(s.transaction_entries.filter(e=>e.transaction_id===s.transactions.at(-1).id).length,2);});
test('cross currency transfer balances each currency through FX offsets',()=>{let s=account(F.empty(),'Dollar','USD','bank',100);s=account(s,'Rupiah');const [a,b]=s.accounts;s=F.transact(s,{type:'transfer',account_id:a.id,destination_id:b.id,amount:50,received:800000,description:'Konversi',date:at});assert.equal(F.balance(s,a.id),5000);assert.equal(F.balance(s,b.id),800000);const sums={};for(const e of s.transaction_entries.filter(e=>e.transaction_id===s.transactions.at(-1).id))sums[e.currency]=(sums[e.currency]||0)+e.amount_minor;assert.deepEqual(sums,{USD:0,IDR:0});});
test('buy and partial sale track fees, weighted cost and realized profit',()=>{let {s,cash,inv,instr}=setup();s=trade(s,cash,inv,instr,'buy',10,10000000,at,100000,0);assert.equal(F.balance(s,cash),9900000);assert.equal(s.positions[0].cost_basis_minor,10100000);s=trade(s,cash,inv,instr,'sell',4,5000000,'2026-10-03T01:00:00Z',50000,10000);const p=s.positions[0];assert.equal(p.quantity_micrograms,6000000);assert.equal(p.cost_basis_minor,6060000);assert.equal(p.realized_pnl_minor,900000);assert.equal(F.balance(s,cash),14840000);assert.equal(p.average_cost,1010000);});
test('selling the entire position clears rounding residue',()=>{let {s,cash,inv,instr}=setup();s=trade(s,cash,inv,instr,'buy',3,10000000);s=trade(s,cash,inv,instr,'sell',1,4000000,'2026-10-03T01:00:00Z');s=trade(s,cash,inv,instr,'sell',2,8000000,'2026-10-03T02:00:00Z');assert.equal(s.positions[0].cost_basis_minor,0);assert.equal(s.positions[0].quantity_micrograms,0);assert.equal(s.positions[0].realized_pnl_minor,2000000);});
test('oversells and backdated sells are rejected atomically',()=>{let {s,cash,inv,instr}=setup();s=trade(s,cash,inv,instr,'buy',3,3000000);const before=JSON.stringify(s);assert.throws(()=>trade(s,cash,inv,instr,'sell',4,4000000,'2026-10-03T01:00:00Z'),/melebihi/);assert.throws(()=>trade(s,cash,inv,instr,'sell',1,1000000,'2026-10-02T01:00:00Z'),/melebihi/);assert.equal(JSON.stringify(s),before);});
test('opening gold has no cash movement; unknown basis yields unknown realized profit',()=>{let {s,cash,inv}=setup();s=F.createGold(s,{account_id:inv,name:'Warisan',purity:75,grams:5,cost:'',date:at});const instr=s.instruments.at(-1).id;assert.equal(F.balance(s,cash),20000000);assert.equal(F.position(s,inv,instr).cost_basis_minor,null);s=trade(s,cash,inv,instr,'sell',5,5000000,'2026-10-03T01:00:00Z');assert.equal(F.position(s,inv,instr).realized_pnl_minor,null);assert.equal(F.position(s,inv,instr).cost_basis_minor,0);});
test('income categories and balance correction create ledger records',()=>{let s=account(F.empty());const aid=s.accounts[0].id;s=F.transact(s,{type:'income',account_id:aid,amount:100,description:'Gaji',new_category:'Gaji',date:at});assert.equal(s.categories.at(-1).name,'Gaji');s=F.updateAccount(s,aid,{name:'Dompet',note:'',balance:60});assert.equal(F.balance(s,aid),60);assert.equal(s.transactions.at(-1).transaction_type,'adjustment');assert.equal(s.transaction_entries.at(-2).amount_minor,-40);});
test('archive refuses nonzero balances and preserves transaction history',()=>{let s=account(F.empty(),'Credit','IDR','credit_card',-1000);assert.throws(()=>F.archive(s,s.accounts[0].id));const aid=s.accounts[0].id;s=F.updateAccount(s,aid,{name:'Credit',balance:0});const count=s.transactions.length;s=F.archive(s,aid);assert.equal(s.accounts[0].status,'archived');assert.equal(s.transactions.length,count);});
test('backup import rejects unbalanced ledger and broken references',()=>{let {s,cash,inv,instr}=setup();s=trade(s,cash,inv,instr);const bad=F.clone(s);bad.transaction_entries[0].amount_minor++;assert.throws(()=>F.read(bad),/seimbang/);const broken=F.clone(s);broken.investment_transactions[0].instrument_id='missing';assert.throws(()=>F.read(broken),/investasi/);});
test('positions from backup are recomputed instead of trusting stale cache',()=>{let {s,cash,inv,instr}=setup();s=trade(s,cash,inv,instr);s.positions[0].quantity_micrograms=999;assert.equal(F.read(s).positions[0].quantity_micrograms,10000000);});
test('v1 migration preserves fiat, gold, purity, unknown basis and market',()=>{const old={version:1,assets:[{id:'a',type:'fiat',name:'Cash',location:'',note:'',currency:'USD',balance:10.25},{id:'b',type:'gold',name:'Ring',location:'Safe',note:'',grams:5,purity:75,cost:null}],events:[],market:null};const s=F.read(old);assert.equal(s.version,2);assert.equal(F.balance(s,s.accounts[0].id),1025);assert.equal(s.positions[0].quantity_micrograms,5000000);assert.equal(s.instruments[0].purity,75);assert.equal(s.positions[0].cost_basis_minor,null);assert.equal(old.version,1);});
function harness(fetcher=async()=>{throw Error('offline')}, backend=undefined){const elements=new Map();const el=key=>{if(!elements.has(key))elements.set(key,{textContent:'',innerHTML:'',hidden:false,style:{},classList:{toggle(){}},elements:{type:{},account_id:{},destination_id:{}},reset(){},showModal(){},close(){}});return elements.get(key);};const storage=new Map();const ctx=vm.createContext({Finance:F,CloudStore:backend,Intl,Date,JSON,Number,String,Object,Array,Set,Error,Math,Promise,AbortSignal,fetch:fetcher,document:{querySelector:el,querySelectorAll:()=>[],body:{classList:{add(){},remove(){}}}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout,console});vm.runInContext(fs.readFileSync('app.js','utf8'),ctx);return {run:code=>vm.runInContext(code,ctx),el};}
test('fresh market quote converts ounce and separates market records',async()=>{const h=harness(async url=>({ok:true,json:async()=>url.includes('gold-api')?{price:3110.34768,updatedAt:at}:{result:'success',rates:{USD:1,IDR:16000,EUR:.9,SGD:1.25,JPY:150,MYR:4,AUD:1.4,GBP:.8},time_last_update_unix:1790985600}}));await h.run('refreshPrices()');assert.ok(Math.abs(h.run('state.market.goldIDR')-1600000)<.001);assert.equal(h.run('state.exchange_rates.length'),8);assert.equal(h.run('state.transactions.length'),0);});
test('failed refresh retains cached prices',async()=>{const h=harness();h.run(`state.market={mode:'spot',goldIDR:1800000,goldAt:'${at}',fxAt:'${at}',fetchedAt:'${at}',rates:{USD:1,IDR:16000}}`);await h.run('refreshPrices()');assert.equal(h.run('state.market.goldIDR'),1800000);assert.match(h.el('#price-status').textContent,/gagal/);});
test('gold valuation respects purity and missing FX remains unknown',()=>{const h=harness();h.run('state.market={goldIDR:2000000,rates:{}}');assert.equal(h.run('valueOf({type:"gold",grams:10,purity:75})'),15000000);assert.equal(h.run('valueOf({type:"fiat",balance:10,currency:"USD"})'),null);assert.equal(h.run('esc("<img onerror=x>")'),'&lt;img onerror=x&gt;');});
test('activity shows outgoing transfer and correct direction even when imported entries are reordered',()=>{
  const h=harness();h.run(`state=F.createAccount(state,{name:'Source',currency:'USD',account_type:'bank',balance:100});state=F.createAccount(state,{name:'Destination',currency:'IDR',account_type:'cash',balance:0});state=F.transact(state,{type:'transfer',account_id:state.accounts[0].id,destination_id:state.accounts[1].id,amount:50,received:800000,date:'${at}',description:'Exchange'});state.transaction_entries.reverse();`);
  assert.match(h.run('transactionDisplay(state.transactions.at(-1)).amount'),/-US\$50/);
  assert.equal(h.run('transactionDisplay(state.transactions.at(-1)).accountNames.join(" → ")'),'Source → Destination');
});
test('gold activity shows actual cash including fees and cards escape account notes',()=>{
  const h=harness();h.run(`state=F.createAccount(state,{name:'<b>Bank</b>',currency:'IDR',account_type:'bank',balance:20000000,note:'<img onerror=x>'});state=F.createAccount(state,{name:'Safe',currency:'IDR',account_type:'investment',balance:0});state=F.createGold(state,{name:'Gold',account_id:state.accounts[1].id,grams:0,purity:99.99,cost:''});state=F.transact(state,{type:'buy',account_id:state.accounts[0].id,investment_account_id:state.accounts[1].id,instrument_id:state.instruments[0].id,grams:1,amount:2000000,fee:10000,tax:5000,date:'${at}',description:'Gold purchase'});`);
  assert.match(h.run('transactionDisplay(state.transactions.at(-1)).amount'),/-Rp\s*2\.015\.000/);
  const card=h.run('assetCard(holdings()[0])');assert.ok(card.includes('&lt;b&gt;Bank&lt;/b&gt;'));assert.ok(card.includes('&lt;img onerror=x&gt;'));
});
test('repeated same-timestamp quote upserts instrument price instead of duplicating it',()=>{const h=harness();h.run(`state=F.createAccount(state,{name:'Safe',currency:'IDR',account_type:'investment',balance:0});state=F.createGold(state,{account_id:state.accounts[0].id,name:'Gold',grams:0,purity:75,cost:''});globalThis.m={mode:'spot',goldIDR:2000000,goldAt:'${at}',fxAt:null,fetchedAt:'${at}',rates:{}};commit(withMarket(m));commit(withMarket(m));`);assert.equal(h.run('state.market_prices.length'),1);assert.equal(h.run('state.market_prices[0].price'),1500000);});
test('hosted UI applies a save only after server acknowledges it and rejects overlapping saves',async()=>{let resolveSave,writes=0;const backend={enabled:true,session:()=>new Promise(()=>{}),save:async s=>{writes++;await new Promise(resolve=>resolveSave=resolve);return s;}};const h=harness(undefined,backend);h.run('blocked=false;globalThis.next=F.createAccount(state,{name:"Cloud bank",currency:"IDR",account_type:"bank",balance:100});');const pending=h.run('commit(next)');assert.equal(h.run('state.accounts.length'),0);await assert.rejects(h.run('commit(next)'),/sedang berlangsung/);assert.equal(writes,1);resolveSave();await pending;assert.equal(h.run('state.accounts.length'),1);assert.match(h.el('#sync-status').textContent,/Tersimpan/);});
test('failed hosted save preserves previous state and does not fallback to browser storage',async()=>{const backend={enabled:true,session:()=>new Promise(()=>{}),save:async()=>{throw Object.assign(Error('conflict'),{status:409});}};const h=harness(undefined,backend);h.run('blocked=false;globalThis.next=F.createAccount(state,{name:"Cloud bank",currency:"IDR",account_type:"bank",balance:100});');await assert.rejects(h.run('commit(next)'),/conflict/);assert.equal(h.run('state.accounts.length'),0);assert.equal(h.run('localStorage.getItem(STORAGE)'),null);assert.match(h.el('#sync-status').textContent,/Gagal/);});
